version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: helius_analyzer
      POSTGRES_USER: helius
      POSTGRES_PASSWORD: helius123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U helius"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: